import Head from "next/head";
import Image from "next/image";
import hero from "../public/laptop-hero.png";
import laptop from "../public/laptop.jpg";
import mobile from "../public/mobile.jpg";
import tablet from "../public/tablet.jpg";
import destop from "../public/destop.jpg";
import clockSection from "../public/clock.png";
import mobileSection from "../public/mobile-section.png";
import laptopSection from "../public/laptop-section.png";
import appleSection from "../public/appleSection.png";
import headphonesSection from "../public/headphones.png";
import headphonesSection2 from "../public/headphones2.jpg";
import speakerSection from "../public/speaker.webp";
import speakerSection2 from "../public/speaker2.png";
import headphonesSection4 from "../public/headphonesSection4.jpg";
import keyboard from "../public/keyboard.jpg";
import vr from "../public/vr.jpg";
import laptopSection5 from "../public/laptopSection5.jpg";

import {
  AiOutlineHeart,
  AiOutlineShoppingCart,
  AiOutlineMenu,
} from "react-icons/ai";
import {
  FaHeadset,
  FaTruck,
  FaSyncAlt,
  FaShoppingBag,
  FaFacebook,
  FaTwitterSquare,
  FaInstagram,
  FaCcPaypal,
  FaCcVisa,
  FaCcMastercard,
} from "react-icons/fa";
import { GiHamburgerMenu } from "react-icons/gi";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shoping Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" max-w-screen-2xl m-auto">
        <section className="bg-gradient-to-tl from-blue-600 to-violet-500">
          <nav className=" bg-transparent h-20 w-full flex flex-row justify-between">
            <input type={"checkbox"} id="check" className="hidden"></input>

            <label className="text-white uppercase font-bold leading-[80px] pl-12 md:leading-[80px]  md:pl-24 md:text-4xl text-3xl">
              Relap
            </label>

            <ul className="float-right mr-10 lg:flex leading-[80px] space-x-4 text-white font-bold uppercase rounded fixed lg:relative h-[100vh] lg:h-0 w-[100%] lg:w-fit top-20 lg:top-0 left-[-100%] lg:left-0 transition-all duration-300 lg:transition-none text-center backdrop-blur-sm">
              <li>
                <a href="#">Store</a>
              </li>
              <li>
                <a href="#">Features</a>
              </li>
              <li>
                <a href="#">About</a>
              </li>
              <li>
                <a href="#">Blog</a>
              </li>
              <li>
                <a href="#">News</a>
              </li>
            </ul>

            <div className="text-5xl flex justify-center gap-3 py-4 text-gray-600 dark:text-gray-400 md:gap-6">
              <AiOutlineHeart className=" cursor-pointer hover:scale-110 hover:transition-all" />

              <AiOutlineShoppingCart className=" cursor-pointer hover:scale-110 hover:transition-all" />
            </div>

            <label className="hidden py-5 mx-5 md:block">
              <span className="sr-only">Search</span>
              <span className="absolute inset-y-0 left-0 flex items-center pl-2">
                <svg
                  className="h-5 w-5 fill-slate-300"
                  viewBox="0 0 20 20"
                ></svg>
              </span>

              <input
                className="placeholder:italic placeholder:text-slate-400 block bg-white w-40 border border-slate-300 rounded-md py-2 pl-3 pr-3 shadow-sm focus:outline-none focus:border-sky-500 focus:ring-sky-500 focus:ring-1 sm:text-sm"
                placeholder="Search for anything..."
                type="text"
                name="search"
              />
            </label>

            <label
              for="check"
              className="float-right text-white text-3xl leading-[80px] mt-6 mr-10 lg:hidden"
            >
              <GiHamburgerMenu />
            </label>
          </nav>

          <div className="lg:flex lg:flex-row-reverse pt-40 pb-20">
            <div className="text-left p-10 py-20">
              <h4 className="text-xl font-medium py-2 text-gray-300">
                MINIM VENIAM
              </h4>

              <h2 className="text-5xl font-bold py-2">UT LABORE ET DOLAORE</h2>
              <p className=" text-white max-w-xl">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit
                maxime accusantium sed! Odio repellat illo esse magni autem
                perspiciatis nostrum totam cum aliquid? Provident at debitis
                eos! Qui, aut voluptate.
              </p>

              <button className="bg-yellow-500 text-white px-10 mt-2 py-3 border-none rounded-full hover:scale-110 hover:translate-all">
                Buy now
              </button>
            </div>

            <div className="mx-2 w-1/1 h-1/1 lg:w-1/2 lg:h-1/2">
              <Image
                src={hero}
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>

        <section>
          <div className="shadow-lg p-10 rounded-xl my-10 lg:flex">
            <div className="flex justify-between py-5">
              <div className="text-4xl text-violet-700 py-2 px-4">
                <FaTruck />
              </div>
              <div>
                <h2 className="text-3xl font-bold py-3">Quis nostrud</h2>
                <p className="text-gray-600 py-2">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Sapiente, rerum. Modi, vero.
                </p>
              </div>
            </div>

            <div className="flex justify-between py-5">
              <div className="text-4xl text-violet-700 py-2 px-4">
                <FaHeadset />
              </div>
              <div>
                <h2 className="text-3xl font-bold py-3">Quis nostrud</h2>
                <p className="text-gray-600 py-2">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Sapiente, rerum. Modi, vero.
                </p>
              </div>
            </div>

            <div className="flex justify-between py-5">
              <div className="text-4xl text-violet-700 py-2 px-4">
                <FaSyncAlt />
              </div>
              <div>
                <h2 className="text-3xl font-bold py-3">Quis nostrud</h2>
                <p className="text-gray-600 py-2">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Sapiente, rerum. Modi, vero.
                </p>
              </div>
            </div>

            <div className="flex justify-between py-5">
              <div className="text-4xl text-violet-700 py-2 px-4">
                <FaShoppingBag />
              </div>
              <div>
                <h2 className="text-3xl font-bold py-3">Quis nostrud</h2>
                <p className="text-gray-600 py-2">
                  Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Sapiente, rerum. Modi, vero.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="text-center lg:flex lg:flex-col">
            <h4 className="font-bold pt-20">NATUS ERROR</h4>
            <h2 className="text-4xl font-bold pb-5">Unde omnis iste</h2>

            <p className="text-gray-500 mx-auto max-w-3xl leading-6">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Laudantium, ut.
              Blanditiis debitis quia, animi eum recusandae architecto!
            </p>
          </div>

          <div className="my-10 lg:flex">
            <div className="my-10">
              <div className="w-80 h-80 mx-auto md:w-1/2 md:h-1/2">
                <Image
                  src={laptop}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <ul className="text-center">
                <li className="text-gray-500 py-2">
                  <a href="#">Commodo</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Consuqeta</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Duis aretis</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Irure dolore</a>
                </li>
                <li className="font-bold py-2">
                  <a href="#">See all</a>
                </li>
              </ul>
            </div>

            <div className="my-10">
              <div className="w-80 h-80 mx-auto md:w-1/2 md:h-1/2">
                <Image
                  src={mobile}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <ul className="text-center">
                <li className="text-gray-500 py-2">
                  <a href="#">Commodo</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Consuqeta</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Duis aretis</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Irure dolore</a>
                </li>
                <li className="font-bold py-2">
                  <a href="#">See all</a>
                </li>
              </ul>
            </div>

            <div className="my-10">
              <div className="w-80 h-80 mx-auto md:w-1/2 md:h-1/2">
                <Image
                  src={tablet}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <ul className="text-center">
                <li className="text-gray-500 py-2">
                  <a href="#">Commodo</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Consuqeta</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Duis aretis</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Irure dolore</a>
                </li>
                <li className="font-bold py-2">
                  <a href="#">See all</a>
                </li>
              </ul>
            </div>

            <div className="my-10">
              <div className="w-80 h-80 mx-auto md:w-1/2 md:h-1/2">
                <Image
                  src={destop}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <ul className="text-center">
                <li className="text-gray-500 py-2">
                  <a href="#">Commodo</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Consuqeta</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Duis aretis</a>
                </li>
                <li className="text-gray-500 py-2">
                  <a href="#">Irure dolore</a>
                </li>
                <li className="font-bold py-2">
                  <a href="#">See all</a>
                </li>
              </ul>
            </div>
          </div>
        </section>

        <section className=" bg-red-100">
          <div className="text-center py-16 lg:flex lg:flex-col">
            <h4 className="font-bold py-3">DESERUNT</h4>
            <h2 className="text-4xl font-bold pb-5">Mollit anim</h2>
          </div>

          <div className="pb-10 lg:grid lg:grid-cols-3 lg:gap-y-5 lg:grid-flow-row-dense">
            <div className="bg-white mx-3 shadow-2xl lg:row-span-2 lg:h-auto lg:aspect-square">
              <h3 className="text-2xl font-bold pt-5 px-5">
                Sed ut perspiciatis
              </h3>

              <p className="text-gray-500 pt-2 px-5">
                Lorem ipsum dolor sit, amet consectetur.
              </p>

              <button className=" text-violet-600 font-medium px-10 my-3 ml-5 py-3 ring-2 ring-violet-500 ring-inset rounded-full hover:transition-all hover:scale-110">
                Shop now
              </button>

              <div className=" w-1/2 h-1/2 my-5 pb-10 mx-auto lg:w-1/2 lg:h-1/2">
                <Image
                  src={appleSection}
                  width={"100%"}
                  height={"100%"}
                />
              </div>
            </div>

            <div className="bg-white mx-3 shadow-2xl">
              <h3 className="text-2xl font-bold pt-5 px-5">
                Totam rem aperiam
              </h3>
              <p className="font-bold py-2 px-5">$199</p>
              <div className="w-1/2 h-1/2 my-5 pb-10 mx-auto lg:w-1/2 lg:h-1/2">
                <Image
                  src={mobileSection}
                  width={"100%"}
                  height={"100%"}
                />
              </div>
            </div>

            <div className="bg-white mx-3 shadow-2xl">
              <h3 className="text-2xl font-bold pt-5 px-5">Eaque ipsa</h3>
              <p className="font-bold py-2 px-5">$99</p>
              <div className="w-1/2 h-1/2 my-5 pb-10 mx-auto lg:w-1/2 lg:h-1/2">
                <Image
                  src={clockSection}
                  width={"100%"}
                  height={"100%"}
                />
              </div>
            </div>

            <div className="bg-white mx-3 shadow-2xln lg:col-span-2">
              <div className="lg:flex lg:justify-between">
                <div>
                  <h3 className="text-2xl font-bold pt-5 px-5">Eaque ipsa</h3>
                  <p className="font-bold py-2 px-5">$99</p>
                  <button className=" text-pink-600 font-medium px-10 my-3 ml-5 py-3 ring-2 ring-pink-500 ring-inset rounded-full hover:transition-all hover:scale-110">
                    Shop now
                  </button>
                </div>

                <div className="w-1/2 h-1/2 mb-3 pb-10 mx-auto lg:w-1/2 lg:h-1/2">
                  <Image
                    src={laptopSection}
                    width={"100%"}
                    height={"100%"}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-gray-100">
          <div className="flex flex-col justify-between pb-10 md:flex md:flex-row lg:flex lg:flex-row">
            <h2 className="text-4xl font-bold pl-5 pt-5 lg:text-5xl lg:pl-40">
              Unde omnis iste
            </h2>

            <ul className="flex flex-wrap pt-10 pr-10 lg:flex  ">
              <li className="text-gray-500 pl-5 hover:text-gray-900 hover:font-bold">
                <a href="#">Phones</a>
              </li>
              <li className="text-gray-500 pl-5 hover:text-gray-900 hover:font-bold">
                <a href="#">Electronics</a>
              </li>
              <li className="text-gray-500 pl-5 hover:text-gray-900 hover:font-bold">
                <a href="#">Appliances</a>
              </li>
              <li className="text-gray-500 pl-5 hover:text-gray-900 hover:font-bold">
                <a href="#"> Clothes</a>
              </li>
              <li className="text-gray-500 pl-5 hover:text-gray-900 hover:font-bold">
                <a href="#"></a>Kids
              </li>
            </ul>
          </div>

          <div className="flex flex-col lg:flex-row">
            <div className=" shadow-lg mx-5 my-20">
              <Image
                src={headphonesSection}
                width={"100%"}
                height={"100%"}
              />

              <h2 className="text-3xl font-bold py-2 pl-3">
                Quis nostrud uterui
              </h2>
              <p className="font-bold py-2 pl-3">$180</p>
            </div>

            <div className="shadow-lg mx-5 my-20">
              <Image
                src={headphonesSection2}
                width={"100%"}
                height={"100%"}
              />

              <h2 className="text-3xl font-bold py-2 pl-3">
                Puert tutino uterui
              </h2>
              <p className="font-bold py-2 pl-3">$180</p>
            </div>

            <div className="shadow-lg mx-5 my-20">
              <Image
                src={speakerSection}
                width={"100%"}
                height={"100%"}
              />

              <h2 className="text-3xl font-bold py-2 pl-3">
                Puert tutino uterui
              </h2>
              <p className="font-bold py-2 pl-3">$180</p>
            </div>

            <div className="shadow-lg mx-5 my-20">
              <Image
                src={speakerSection2}
                width={"100%"}
                height={"100%"}
              />

              <h2 className="text-3xl font-bold py-2 pl-3">
                Puert tutino uterui
              </h2>
              <p className="font-bold py-2 pl-3">$180</p>
            </div>
          </div>
        </section>

        <section className=" bg-red-100">
          <div className="pb-20">
            <div className="mb-10 lg:flex lg:justify-between">
              <h2 className="text-4xl font-bold pl-5 pt-5 lg:text-5xl lg:pl-40">
                Magani dolores
              </h2>
              <h3 className="text-xl pt-5 pl-5 font-bold md:pt-10 md:pr-20 lg:pt-10 lg:pr-20">
                12:17:08:42
              </h3>
            </div>

            <div className="flex flex-col lg:flex lg:flex-row lg:justify-around">
              <div className=" bg-slate-50 shadow-2xl my-10 flex flex-col lg:h-72 lg:w-60 lg:mx-20 lg:text-left">
                <h3 className="pl-10 pt-5 text-xl font-bold">Volupdate</h3>

                <ul className="pl-5 py-5 flex flex-wrap lg:flex lg:flex-col">
                  <li className="text-gray-500 pl-5 pt-2 hover:text-gray-900 hover:font-bold">
                    <a href="#">Phones</a>
                  </li>
                  <li className="text-gray-500 pl-5 pt-2 hover:text-gray-900 hover:font-bold">
                    <a href="#">Electronics</a>
                  </li>
                  <li className="text-gray-500 pl-5 pt-2 hover:text-gray-900 hover:font-bold">
                    <a href="#">Appliances</a>
                  </li>
                  <li className="text-gray-500 pl-5 pt-2 hover:text-gray-900 hover:font-bold">
                    <a href="#"> Clothes</a>
                  </li>
                  <li className="text-gray-500 pl-5 pt-2 hover:text-gray-900 hover:font-bold">
                    <a href="#"></a>Kids
                  </li>
                </ul>
              </div>

              <div className="mx-auto h-80 w-80 lg:h-96 lg:w-96 lg:mx-20 ">
                <Image
                  src={headphonesSection4}
                  width={"100%"}
                  height={"100%"}
                />
              </div>

              <div className="bg-slate-50 shadow-2xl pb-10 pl-5 px-3 mx-10 lg:w-96">
                <h3 className="text-3xl font-bold py-3">
                  Quis autem vel eum iure reprehenderit
                </h3>
                <h3 className="text-2xl font-bold">$199</h3>
                <p className="py-5 text-gray-500">
                  Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                  Possimus natus voluptatibus id dicta, tenetur facilis
                  architecto unde enim nesciunt quisquam animi, aut ratione
                  provident eos quod, repellat quia esse qui vel excepturi
                  labore odit debitis ipsam iusto. Doloremque quia totam,
                  perferendis odit sint laboriosam hic atque recusandae ut alias
                  nisi.
                </p>
                <button className="text-xl font-medium border-none rounded-full px-10 py-3 bg-purple-500 text-white hover:scale-110 hover:translate-all">
                  Add to cart
                </button>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20">
            <div className="text-left mx-10">
              <h2 className="font-bold pl-2">VELIT ESSE</h2>
              <h4 className="text-5xl font-bold">Quam nihili</h4>
            </div>

            <div className="lg:flex lg:flex-row">
              <div className="shadow-2xl mt-10 mx-10">
                <Image
                  src={keyboard}
                  width={"100%"}
                  height={"100%"}
                />
                <h4 className="font-bold text-xl pt-5 pl-5">
                  Vel illum qui dolorem eum fugiat
                </h4>
                <p className="font-medium pl-5 pb-5">June 01/2022</p>
              </div>

              <div className=" shadow-2xl mt-10 mx-10">
                <Image
                  src={vr}
                  width={"100%"}
                  height={"100%"}
                />
                <h4 className="font-bold text-xl pt-5  pl-5">
                  Vel illum qui dolorem eum fugiat
                </h4>
                <p className="font-medium pl-5 pb-5">June 01/2022</p>
              </div>

              <div className=" shadow-2xl mt-10 mx-10">
                <Image
                  src={laptopSection5}
                  width={"100%"}
                  height={"100%"}
                />
                <h4 className="font-bold text-xl pt-5 pl-5">
                  Vel illum qui dolorem eum fugiat
                </h4>
                <p className="font-medium pl-5 pb-5">June 01/2022</p>
              </div>
            </div>
          </div>
        </section>

        <section className=" bg-blue-800">
          <div className="text-center md:flex md:flex-col lg:flex lg:flex-col xl:flex xl:flex-row xl:text-left">
            <div className="py-5 px-5 lg:mx-40">
              <h4 className="font-bold text-white">ODIO DIGNISSIMOS</h4>
              <h2 className=" py-3 text-5xl font-bold text-white">
                Ducimus qui
              </h2>
              <p className="text-gray-400">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                Voluptatibus exercitationem error repudiandae reiciendis
                quisquam maiores tenetur expedita neque velit eaque!
              </p>
            </div>

            <div className="w-80 mx-auto md:w-80 lg:w-96 xl:mt-24 xl:mr-20">
              <label class="block">
                <input
                  type="email"
                  name="email"
                  class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-sky-500 focus:ring-sky-500 block w-full rounded-md sm:text-sm focus:ring-1"
                  placeholder="Your email"
                />
              </label>
            </div>

            <div className="pb-10 lg:mt-10 lg:mr-5 xl:mt-20">
              <button className=" bg-yellow-400 text-yellow-50 font-bold my-5 mx-5 py-3 px-10 border-none rounded-full hover:scale-110">
                Subscribe
              </button>
            </div>
          </div>
        </section>

        <section>
          <div className="py-20 md:flex lg:flex lg:justify-between">
            <div className=" w-60 mx-auto text-center ">
              <h3 className="font-bold pt-5">Tempor</h3>
              <ul className=" py-5">
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Simillque</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Deserunt molilt anim</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Sed ut preprectis</a>
                </li>
              </ul>
            </div>

            <div className=" w-60 mx-auto text-center ">
              <h3 className="font-bold pt-5">Sunt in despero</h3>
              <ul className=" py-5">
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Sunt in cupla</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Molit anim</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Sreprectis</a>
                </li>
              </ul>
            </div>

            <div className="  w-60 mx-auto text-center">
              <h3 className="font-bold pt-5">Qui official</h3>
              <ul className=" py-5">
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Deserunt</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Politali</a>
                </li>
                <li className="text-gray-500 pt-2 hover:text-gray-900 hover:font-bold">
                  <a href="#">Lobrolurl</a>
                </li>
              </ul>
            </div>

            <div className=" w-60 mx-auto text-center ">
              <h3 className="font-bold pt-5">Magna</h3>
              <p className=" pt-2 text-gray-500">232 diginissimo terol,42</p>
              <p className=" pt-2 text-gray-500">minimu@info.com</p>
              <p className=" pt-2 text-gray-500">+1 (256) 569 992 01</p>
            </div>
          </div>
        </section>

        <section>
          <hr class="my-4 mx-auto w-full h-1 bg-gray-100 dark:bg-gray-500"></hr>

          <div className="py-10 lg:flex lg:justify-around">
            <div className="font-bold text-gray-500 text-center pt-10">
              <h3>Copyright2022. All rights Reserved.</h3>{" "}
            </div>

            <div className="text-5xl flex justify-center gap-7 py-10  text-gray-600 dark:text-violet-500  md:gap-16 lg:gap-16">
              <FaFacebook className=" cursor-pointer hover:scale-110 hover:transition-all" />

              <FaTwitterSquare className=" cursor-pointer hover:scale-110 hover:transition-all" />

              <FaInstagram className=" cursor-pointer hover:scale-110 hover:transition-all" />
            </div>

            <div>
              <div className="text-5xl flex justify-center py-10 gap-7 text-gray-600 dark:text-violet-500  md:gap-16 lg:gap-16">
                <FaCcPaypal className=" cursor-pointer hover:scale-110 hover:transition-all" />

                <FaCcVisa className=" cursor-pointer hover:scale-110 hover:transition-all" />

                <FaCcMastercard className=" cursor-pointer hover:scale-110 hover:transition-all" />
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
